sonic-net/sonic-linux-kernel

patch/config-mlnx-sn2700.patch
=> bug fix: regenerate config-mlnx-sn2700.patch to apply correctly

patch/config-ingrasys-s9100.patch, patch/driver-pca954x-i2c-mux-force-deselect-on-exit-flag.patch, patch/series
* Add ingrasys s9100 kernel config
* Add PCA954x I2C force deselect on exit flag
Signed-off-by: Wade He chihen.he@gmail.com
=> Add ingrasys switch s9100 kernel patches

patch/driver-support-tun-config-carrier-enable.patch, patch/series
Added enable/disable carrier ability in TUN/TAP driver. It used by SONiC code.
=> Update Tun/Tap by adding enable/disable carrier ability.

patch/driver-support-optoe-EOF_fix.patch, patch/series
Added patch: 'driver-support-optoe-EOF_fix.patch' to patch directory
Added the patch to 'series'
Signed-off-by: Don Bollinger
=> Update to optoe driver to improve EOF handling

patch/config-arista-dps1900.patch, patch/driver-hwmon-pmbus-dps1900.patch, patch/series
Hi there,
Here is an implementation of the module dps1900 to support Delta DPS1900 devices.
Thanks for your review.
=> Support Delta DPS1900

Makefile, patch/preconfig/changelog.patch
=> upgrade kernel to debian 4.9.110-3+deb9u1

patch/config-inventec-d7032.patch, patch/series
enable GPIO_ICH for Invetnec platform
=> enable GPIO_ICH

patch/driver-uart-fix-race-between-uart_put_char-and-uart_shutdown.patch, patch/series
backing port a5ba1d95e46ecaea638ddd7cd144107c783acb5d
=> uart: fix race between uart_put_char() and uart_shutdown()

Makefile
- Make kernel build fail on any error
- commit original files so "git am" would succeed
- commit changed files
Signed-off-by: Ying Xie <ying.xie@microsoft.com>
=> [Kernel] fix kernel build errors

patch/driver-uart-fix-race-in-uart_write.patch, patch/series
=> uart: fix race in uart_write()

patch/driver-uart-fix-another-race-between-uart_put_char-and-uart_shutdow.patch
=> yet another uart race condition fix

patch/0036-watchdog-mlx-wdt-kernel-upstream-and-wd-type2-change.patch, patch/0037-mlxsw-Align-code-with-kernel-v-5.1.patch, patch/0038-mlxsw-core-Add-check-for-split-port-during-thermal-z.patch, patch/series
It includes:
Latest changes in watchdog driver.
Latest changes in ASIC thermal driver.
Fix for split port for ASIC I2C driver.
Signed-off-by: Vadim Pasternak <vadimp@mellanox.com>
=> Mellanox drivers backport latest code accepted for v5.1

patch/e1000-Do-not-perform-reset-in-reset_task-if-we-are-a.patch, patch/series
=> e1000: Do not perform reset in reset_task if we are already down

azure-pipelines.yml
=> [ci]: enable pr build for master/202012/201911/201811 branches

Makefile, patch/preconfig/series
=> [201811]: security update kernel to 4.9.246

patch/driver-hwmon-pmbus-dni_dps460-add-status-attributes.patch, patch/series
Signed-off-by: Arun Saravanan Balachandran <Arun_Saravanan_Balac@dell.com>
Add attributes to retrieve PMBus status command codes
=> [201811] dni_dps460: Add attributes to retrieve PMBus status command codes

azure-pipelines.yml
=> [ci]: remove 201911 suffix

azure-pipelines.yml
=> [ci]: remove 201811 suffix

CODEOWNERS
=> [github]: add code owner

.azure-pipelines/build-template.yml
Old agent pool is deprecated. Migrate to new agent pool.
=> [ci] Migrate to sonicbld1es agent pool.
