sonic-net/sonic-linux-kernel

patch/driver-support-intel-avoton-ethernet-with-broadcom-phy.patch
patch/driver-support-new-broadcom-phys.patch
patch/series

Patch to support Intel Avoton Ethernet driver with  Broadcom PHY
Signed-off-by: Nadiya.Stetskovych <Nadiya.Stetskovych@cavium.com>

patch for linux igb driver making bcm54616 Broadcom PHY work

---

patch/driver-arista-net-tg3-access-regs-indirectly.patch
patch/driver-arista-net-tg3-dma-mask-4g-sb800.patch
patch/series

Patch to support limitations of the Arista DCS-7050QX-32 with the broadcom tg3 kernel driver.
These caused the kernel to hang during boot.

patch for tg3 driver to fix kernel hang during boot on Arista 7050QX-32

---

patch/linux-3.19-mmc-sdhci-Add-a-quirk-for-AMD-SDHC-transfer-mode-reg.patch
patch/linux-3.19-mmc-sdhci-pci-enable-sdhci-doesn-t-support-hs200-qui.patch
patch/linux-3.19-mmc-sdhci-pci-enable-the-clear-transfer-mode-registe.patch
patch/series

These kernel patches are backport from linux 3.19 to fix mmc issues seen when booting on a DCS-7060CX-32S

Add kernel patches to fix mmc flash issue with DCS-7060CX-32S

---

patch/config-dell-z9100.patch
patch/series

The Dell Z9100 I2C devices are multiplexed behind a series of PCA9547 and PCA9548 muxes. This enables the PCA954x driver support in the kernel to allow access to the System EEPROM and SFP EEPROMs.

Add support for PCA954x I2C mux

---

patch/driver-hwmon-lm75b-update.patch
patch/series

The Celestica Seastone DX010 platform is using the LM75B. Please merge this commit to support LM75B.

Add support for LM75B

---

patch/rtnetlink-catch-EOPNOTSUPP-errors.patch
patch/series

To fix "bridge vlan show" empty result issue.
On platform which has Intel I354 nic as management port,   I354 is capable of SR-IOV,  IGB driver registered igb_ndo_bridge_getlink() and it would be called in rtnl_bridge_getlink().  But SR-IOV is not enabled by default,  igb_ndo_bridge_getlink() returns -EOPNOTSUPP which would cause rtnl_bridge_getlink() to abort the processing and returns empty or partial result to bridge vlan request

rtnetlink: catch -EOPNOTSUPP errors from ndo_bridge_getlink

---

patch/driver-arista-net-tg3-disallow-broadcom-default-mac.patch
patch/series

For Arista platforms, after calling kexec in fast-reboot, the MAC address of management interface is reset to 00:10:18:00:00:00. This patch can recover the MAC with the one previously saved by Arista Aboot.

Disallow resetting to the default mac after kexec

---

patch/driver-arista-net-tg3-disallow-broadcom-default-mac.patch

We once submitted a kernel patch to fix a MAC issue in fast-rebooting by disallowing the broadcom-default MAC. In case of any special situation that 00:10:18:00:00:00 is still needed, we provide this change to relax the disallowing in two cases: 1) the MAC of an interface will be able to be changed to 00:10:18:00:00:00 by "ip link set eth0 address 00:10:18:00:00:00", which was not in our previous change; 2) an interface only having 00:10:18:00:00:00 in its register will be able to be initialized and shown in "ip addr", which was not in our previous change.

Relax the disallowing of broadcom-default MAC in two cases

---

patch/config-arista-7060-cx32s.patch
patch/series

Add the MAX6697 kernel module to the build to allow for the temperature sensor to be used on the Arista 7060CX-32S.
You can verify that the MAX6697 kernel module exists with the command below:
$ find /lib/modules/$(uname -r) | grep max6697

Add MAX6697 kernel module for Arista 7060CX-32S

---

patch/config-mitac-ly1200.patch
patch/driver-hwmon-max31790.patch
patch/driver-i2c-bus-ismt-i801-support-intel-denverton.patch
patch/series

Add  MAX31790 and modify i2c buses kernel driver for MiTAC ly1200
Signed-off-by: Eddy Weng <eddy.weng@mic.com.tw>

Add  MAX31790 and modify i2c buses kernel driver for MiTAC ly1200

---

patch/driver-support-optoe.patch
patch/series

* Add the optoe driver, copied from github.com/opencomputeproject/oom
* Update Makefile to build optoe
* Update Kconfig to conifuge optoe
Signed-off-by: Don Bollinger <don@thebollingers.org>

drivers/misc/eeprom:  Add support for optoe driver

---

patch/linux-3.17-serial-core-Fix-x_char-race.patch
patch/series

- What I did
A fix for a tty race in serial_core.c was added in the 3.17 kernel. Port this patch to SONiC kernel as the first attempt to fix console-stuck issue.

Port a kernel patch as the first attempt to fix console-stuck issue

---

Makefile

Add support to download pre-built Linux kernel Debian packages instead of building from source files.
This change prefers the method of download over build.
Signed-off-by: Ying Xie <ying.xie@microsoft.com>
Note: this PR is better go in after https://github.com/Azure/sonic-buildimage/pull/1837 but it doesn't have to.

[Kernel] support downloading built kernel Debian packages

---

Makefile

use --no-use-server-timestamps when download the build artifacts

---

Makefile
patch/preconfig/changelog.patch

To fix security issue https://security-tracker.debian.org/tracker/CVE-2018-5391
TODO:
1. ~~check PR build, and upload to sonicstorage for downloading~~ Done https://sonic-jenkins.westus2.cloudapp.azure.com/job/common/job/linux-kernel-pr-build/93/
2. merge this PR
3. update sonic-buildimage/rules/linux-kernel.mk

Upgrade kernel to debian 4.9.110-3+deb9u2

---

patch/driver-support-optoe-chunk-offset-fix.patch
patch/series

Correct a panic inducing defect which is triggered on a read (or write)
which begins beyond byte 128, on a byte which is not aligned on a 128 byte
chunk boundary, and which crosses a chunk boundary.

import upstream optoe chunk offset fix

---

patch/0014-mlxsw-qsfp_sysfs-Support-CPLD-version-reading-based-.patch

Change the attribute of mlxsw_qsfp_dmi_set_cpld_num and
mlxsw_qsfp_dmi_table, let them could be called for multiple times during
kernel boot up.
Signed-off-by: Kevin Wang <kevinw@mellanox.com>

Fix a mlnx hardware-management issue

---

patch/0021-Mellanox-backport-patchwork-from-kernels-4.17-4.19.patch
patch/0022-platform-x86-mlx-platform-backport-from-4.19.patch
patch/0023-platform-x86-mlx-platform-Add-support-for-register-a.patch
patch/0024-config-mellanox-fan-configuration.patch
patch/series

It contains the series of Mellanox patches.
The series contains the following patches:   
Mellanox: backport patchwork from kernels 4.17-4.19
Mellanox: add support for register  CPLD3_VER, RST_CUSE. Add NG system type support.
Mellanox: add fan configuration add configuration flag, used by Mellanox systems: 
SENSORS_MLXREG_FAN=m
Signed-off-by: Oleksandr Shamray <oleksandrs@mellanox.com>

Update kernel with the latest upstream pacthes.

---

patch/driver-net-tg3-add-param-short-preamble-and-reset.patch
patch/series

Add "short preamble" parameter for MAC can validate mdio access to some external PHY.
Add "reset" parameter for MAC to reset PHY at driver starting up.
Signed-off-by: roy_lee <roy_lee@accton.com>

Add 2 parameters for driver tg3 can support "short preamble" and "reset".

---

Makefile
patch/preconfig/changelog.patch

See changelog for security fixes:
https://tracker.debian.org/media/packages/l/linux/changelog-4.9.110-3deb9u6
Signed-off-by: Zhenggen Xu <zxu@linkedin.com>
Kernel binaries need to be uploaded by MSFT to Azure so when system can build when procure_method is "download"
===Log ===
linux (4.9.110-3+deb9u6) stretch-security; urgency=high
* [arm64] KVM: Tighten guest core register access from userspace
(CVE-2018-18021)
* [arm64] KVM: Sanitize PSTATE.M when being set from userspace
(CVE-2018-18021)
* xen-netback: fix input validation in xenvif_set_hash_mapping()
(CVE-2018-15471)
-- Salvatore Bonaccorso <carnil@debian.org>  Mon, 08 Oct 2018 08:05:17 +0200
linux (4.9.110-3+deb9u5) stretch-security; urgency=high
[ Salvatore Bonaccorso ]
* irda: Fix memory leak caused by repeated binds of irda …

[security] Upgrade kernel from 4.9.110-3+deb9u2 to 4.9.110-3+deb9u6

---

Makefile
patch/config-l3mdev-cgroup.patch
patch/driver-l3mdev-cgroup.patch
patch/preconfig/packaging-update-abiname-to-8-1.patch
patch/preconfig/series
patch/series

```
admin@str-s6000-on-4:~$ sudo ip link add dev red type vrf table 10
admin@str-s6000-on-4:~$ ip link show type vrf
10: red: <NOARP,MASTER> mtu 65536 qdisc noop state DOWN mode DEFAULT group default qlen 1000
link/ether ce:c7:8c:21:ae:c9 brd ff:ff:ff:ff:ff:ff
admin@str-s6000-on-4:~$ sudo sysctl -w net.ipv4.tcp_l3mdev_accept=1     
net.ipv4.tcp_l3mdev_accept = 1
admin@str-s6000-on-4:~$ sudo ip link set dev eth0 master red
root@str-s6000-on-4:/home/admin# ip route show vrf red
default via 10.3.146.1 dev eth0 
10.3.146.0/23 dev eth0 proto kernel scope link src 10.3.146.113 
admin@str-s6000-on-4:~$ sudo cgcreate -g l3mdev:red
admin@str-s6000-on-4:~$ cgset -r l3mdev.master-device=red red        
admin@str-s6000-on-4:~$ cgexec -g l3mdev:red bash   
root@str-s6000-on-4:/home/admin# apt-get …
```

L3mdev cgroup

---

Makefile
patch/0025-net-udp_l3mdev_accept-support.patch
patch/preconfig/packaging-update-abiname-to-8-2.patch
patch/preconfig/series
patch/series

This commit adds the udp_l3mdev_accept kernel patch
to the linux kernel. This requires an abiname change
from 4.9.0-7-amd64 to 4.9.0-7-1-amd64
Signed-off-by: Harish Venkatraman <Harish_Venkatraman@dell.com>

[sonic-linux-kernel] Abiname change

---

Makefile
patch/changelog.patch

Upgrade kernel from 3.16.57-2 to 3.16.59-1
Signed-off-by: Zhenggen Xu <zxu@linkedin.com>
====
Fix below issues:
linux (3.16.59-1) jessie-security; urgency=high
* New upstream stable update:
https://www.kernel.org/pub/linux/kernel/v3.x/ChangeLog-3.16.58
- net: Set sk_prot_creator when cloning sockets to the right proto
- Bluetooth: hidp: buffer overflow in hidp_process_report (CVE-2018-9363)
- scsi: libsas: defer ata device eh commands to libata (CVE-2018-10021)
- xfs: set format back to extents if xfs_bmap_extents_to_btree
(CVE-2018-10323)
- ext4: only look at the bg_flags field if it is valid (CVE-2018-10876)
- ext4: fix check to prevent initializing reserved inodes
- ext4: verify the depth of extent tree in ext4_find_extent()
(CVE-2018-10877)
- ext4: always check block group bounds in …

Upgrade kernel from 3.16.57-2 to 3.16.59-1

---

patch/0026-mlxsw-qsfp_sysfs-Support-extended-port-numbers-for-S.patch
patch/0027-mlxsw-thermal-monitoring-amendments.patch
patch/0028-watchdog-mlx-wdt-introduce-watchdog-driver-for-Mella.patch
patch/0029-mlxsw-qsfp_sysfs-Support-port-numbers-initialization.patch
patch/0030-update-kernel-config.patch
patch/0031-mlxsw-Align-code-with-kernel-v-5.0.patch
patch/0032-sonic-update-kernel-config-mlsxw-pci.patch
patch/0033-hwmon-pmbus-Fix-driver-info-initialization-in-probe-.patch
patch/0034-mlxsw-thermal-disable-highest-zone-calculation.patch
patch/0035-platform-x86-mlx-platform-Add-CPLD4-register.patch
patch/series

Backport from upstream kernels v4.20, v5.0, v5.1 (next).
Mellanox drivers backport patching from kernels 4.20-5.0
Backport from upstream kernels v4.20, v5.0.
Patches include:
- Amendment for cooling device
- Fix for mlxreg-fan driver
- Fixes for Mellanox systems DMI names.
The list of commits is below:
commit fb7255a923115188ac134bb562d1c44f4f3a413b
Author: Vadim Pasternak <vadimp@mellanox.com>
Date:   Thu Nov 15 17:27:00 2018 +0000
platform/x86: mlx-platform: Convert to use SPDX identifier
Reduce size of duplicated comments by switching to use SPDX identifier.
Signed-off-by: Vadim Pasternak <vadimp@mellanox.com>
Signed-off-by: Darren Hart (VMware) <dvhart@infradead.org>
commit e2883859dd0b4ee6fc70151e417fed8680efaa4b
Author: Vadim Pasternak <vadimp@mellanox.com>
Date:   Thu Nov 15 …

Mellanox drivers backport patching from kernels 4.20-5.0-next

---

patch/0039-mlxsw-core-Prevent-reading-unsupported-slave-address.patch
patch/series

A bug fix to Mellanox drivers:
Prevent reading unsupported slave address from SFP EEPROM 
by testing Diagnostic Monitoring Type byte in EEPROM. 
If some SFP transceiver doesn't support Digital Optical Monitoring (DOM),
thus reading SFP EEPROM slave address 0x51 could return an error.
Add code to detect the availability of DOM support, 
it is verified by reading from zero page Diagnostic Monitoring Type byte 
describing how diagnostic monitoring is implemented by the transceiver. 
Signed-off-by: Kebo Liu kebol@mellanox.com

[Mellanox] bug fix to prevent reading unsupported slave address of SFP eeprom

---

patch/linux-4.16-firmware-dmi-handle-missing-DMI-data-gracefully.patch
patch/series

This is just a cosmetic fix for platforms that doesn't provide any DMI
information. Without this patch this raise an error kernel message which
should actually just be a debug one. This patch does just that.

Backport DMI probe fix from linux-4.16

---

patch/0040-mlxsw-core-add-support-for-Gear-Box-temperatures-in-.patch
patch/0041-mlxsw-minimal-Provide-optimization-for-I2C-bus-acces.patch
patch/series

A new version of Mellanox hw-mgmt package introduced two kernel patches:
new file:   patch/0040-mlxsw-core-add-support-for-Gear-Box-temperatures-in-.patch
new file:   patch/0041-mlxsw-minimal-Provide-optimization-for-I2C-bus-acces.patch
These two patches
1.  Add hwmon interface for inter-connects temperature reading
2.  Provide optimization for I2C bus access

[Mellanox] Add Mellanox kernel patches for new hw-mgmt package

---

patch/driver-hwmon-max6658-fix-write-convrate.patch
patch/series

We found that max6658 sporadically sends a false overtemp alarm during
changing the convrate by hwmon kernel driver. This workaround will fix it by 
forcing to stop conversion before setting the convrate. The false alarm will
trigger reboot and we found it on Arista 7170 switch.

Fix false alarm when writing convrate on max6658

---

patch/0025-mlxsw-qsfp_sysfs-Remove-qsfp-valid-time.patch
patch/series

What I did:  
In some case, after SFP plug in/out the presence status only change after about 120s, this is because of the qsfp caching time set in the kernel. To make the qsfp presence time change in time, we remove the caching time from the kernel.

[Mellanox] Add kernel patch to remove qsfp status caching time

---

Makefile

The official download has been unstable lately and not all build machines
can download the source files.
Moving the source file to more reliable azure storage.
Signed-off-by: Ying Xie <ying.xie@microsoft.com>

[kernel source] download kernel source files from azure storage

---

patch/kernel-enable-psample-and-act_sample-drivers.patch
patch/mellanox-backport-introduce-psample-a-new-genetlink-channel.patch
patch/mellanox-backport-introduce-tc-sample-action.patch
patch/series

- What I did
Backport psample and act_sample drivers to sonic linux kernel  4.9.
- How I did it
Both psample and act_sample are needed for sflow feature. 
psample driver is needed for collecting samples from the interfaces at the kernel level.
act_sample driver is needed for the 'tc' command to be able to program the sampling configurations into the interfaces at the kernel level.  
psample and act_sample drivers are not back-ported  yet to the linux kernel version that sonic-linux-kernel is using. Hence, I have taken the patches for both the drivers and included it in our sonic kernel.
- How to verify it
- Using Azure/sonic-buildimage#3251 changes, build a sonic image
This step would include the psample and act_sample drivers into the sonic-linux-kernel.
Also, it would install the …

[sflow]: backport psample and act_sample drivers, needed for sonic-vs platform

---

patch/0042-mlxsw-core-Skip-port-split-entries-in-hwmon-subsyste.patch
patch/0043-mellanox-platform-Backporting-Melanox-drivers-from-v.patch
patch/0044-mlxsw-minimal-Provide-optimization-for-module-number.patch
patch/0045-mlxsw-minimal-Add-validation-for-FW-version.patch
patch/series

Added 4 patches:
0042-mlxsw-core-Skip-port-split-entries-in-hwmon-subsyste.patch
Skip split entries in hwmon. Run loop for port creation over maximum port counter, otherwise
in some split configuration with holes, some last modules can be missed.
0043-mellanox-platform-Backporting-Melanox-drivers-from-v.patch
Required for new Mellanox systems and also contains bugfixes.
0044-mlxsw-minimal-Provide-optimization-for-module-number.patch
Use new filed ‘num_of_modules’ in MGPIR register in order to get the number of modules supported by system directly from system configuration, instead of getting it from port to module mapping info.
0045-mlxsw-minimal-Add-validation-for-FW-version.patch
Add validation for FW version in order to prevent driver initialization in case FW version is older than …

[Mellanox] Add hw-management driver patches

---

Makefile
patch/preconfig/changelog.patch

upgrade kernel to version linux_4.9.168-1+deb9u5
- pick up security patches
Signed-off-by: Ying Xie <ying.xie@microsoft.com>

[kernel] upgrade to version linux_4.9.168-1+deb9u5

---

patch/0046-mfd-lpc-ich-extend-with-additional-chipsets-support.patch
patch/series

Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>
This patch extends chipset types supported by 'lpc_ich' driver:
1. Apollo Lake SoC
2. Gemini Lake SoC
3. Cougar Mountain SoC

Extend 'lpc_ich' driver with additional chipsets support

---

patch/0000-net-ipv6-ll-anycast-mcast-routes-on-dev.patch
patch/series

IPv6 host and subnet anycast route in VRF to be configured with nhop interface as actual netdev instead of VRF L3MDEV
When we configure IPv6 route with plen <127(127 is used for inter router
links), kernel auto-generates subnet-router anycast address. This is as
per RFC 4291(section Required Anycast address) and RFC 6164. In kernel
version 4.9.x these routes are autogenerated with nhop interface as VRF
L3MDEV instead of the interface on which these address are configured.
Also host address(/128) were also pointing to same L3MDEV.
This was creating issue esp during warm-reboot since FRR installs these
routes via fpm to APP_DB ROUTE_TABLE pointing to VRF name. Warm boot
will be blocked since routerorch will keep waiting for these routes to
be uninstalled.
Also these routes will not be …

IPv6 host and subnet anycast route in VRF to be configured with nhop

---

patch/0000-net-Fix-netdev-adjacency-tracking.patch
patch/series

This was observed when we have below configuration: This happens when we
have ~100 vlans configured:
Sequence:
1. Physical ports member of PortChannel which is member of Vlan(s) and
this VLAN is in VRF and IP is assigned.
2. Move PortChannel out of Vlan(s) and bind to VRF and assign IP (Note:
there is no config save here)
3. Perform config reload
4. Repeat step 2
5. Perform VRF delete
This will cause unregister_netdev for VRF. This is due to netdev
adjacency graph maintained in kernel is not cleaned up properly.
Netdev adjacency will be maintained between VRF-Vlan, VRF-PortChannel,
VRF-Ethernet*. This is maintained for all possible combinations which
forms graph.
But during cleanup, Vlan netdev adjacency(and all adj below it in
hierarchy) unlink doesnt cleanup all adjacency with VRF due …

Unregister_netdev VRF obsreved and kernel hangs during vrf delete

---

patch/0001-net-ipv6-Allow-shorthand-delete-of-all-nexthops-in-m.patch
patch/series

This was already supported by IPv4 but missing for IPv6. This commit
brings shorthand delete of IPv6 multipath routes in kernel.
Successive delete of multi-path routes(32 paths) was not clearing all routes in kernel though frr was sending RTM_DELROUTE when last nexthop was getting deleted. Reason being For IPv6 delete route in kernel, expects all nhops to be sent. On counter part, IPv4 route delete in kernel does NOT expect all nhops to be sent. FRR currently doesnt send any nhops when operation is RTM_DELROUTE for both IPv4 & IPv6.
back porting below changes from newer version of kernel
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/net/ipv6/route.c?h=v4.14.144&id=0ae8133586ad1c9be894411aaf8b17bb58c8efe5
After importing above patch, there were no stale IPv6 …

Allow shorthand delete of all nexthops in multipath IPv6 routes

---

patch/0026-4.14.-15-56-platform-x86-mlx-platform-Fix-parent-device-in-i2c-mux-reg-device-registration.patch
patch/series

Patch fixes parent device parameter in a call to
platform_device_register_resndata() for "i2c-mux-reg".
It solves the race during initialization flow while 'i2c_mlxcpld.1' is
removing after probe, while 'i2c-mux-reg.0' is still in probing flow.
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>

[kernel] add patch for mlx-platform: Fix parent device in i2c-mux-reg device registration

---

patch/net-backport-ipv6-missing-route.patch
patch/series

The below patch has been backported from latest linux to fix the kernel crash reported in  [Azure/sonic-builimage#3831](https://github.com/Azure/sonic-buildimage/issues/3831)
'ipv6: Handle missing host route in __ipv6_ifa_notify'
https://github.com/torvalds/linux/commit/2d819d250a1393a3e725715425ab70a0e0772a71#diff-0907850728440370acc820310df76f30

Add linux patch to fix 'ipv6: Handle missing host route in __ipv6_ifa_notify'

---

patch/0048-mlxsw-core-Skip-thermal-zone-operations-initializati.patch
patch/0049-thermal-Fix-use-after-free-when-unregistering-therma.patch
patch/0050-mlxsw-core-Drop-creation-of-thermal-to-hwmon-sysfs-i.patch
patch/0051-mlxsw-core-Skip-thermal-zones-threshold-setting-duri.patch
patch/0052-platform-x86-mlx-platform-Add-more-detention-for-sys.patch
patch/series

patch/0048-mlxsw-core-Skip-thermal-zone-operations-initializati.patch
patch/0049-thermal-Fix-use-after-free-when-unregistering-therma.patch
patch/0050-mlxsw-core-Drop-creation-of-thermal-to-hwmon-sysfs-i.patch
patch/0051-mlxsw-core-Skip-thermal-zones-threshold-setting-duri.patch
patch/0052-platform-x86-mlx-platform-Add-more-detention-for-sys.patch

[Mellanox] Add the driver patches for hw-mgmt V7.0000.2308

---

patch/Support-for-fullcone-nat.patch
patch/series

Changes done in the kernel to ensure 3-tuple uniqueness of the conntrack entries for the fullcone nat functionality.
- Hashlist is maintained for the 3-tuple unique keys (Protocol/Source IP/Port) for all the conntrack entries.
- When NAT table rules are created with the fullcone option, the SNAT/POSTROUTING stage ensures the ports from the pool are picked up in such a way that the 3-tuple is uniquely assigned.
- In the DNAT/POSTROUTING stage, the fullcone behavior is ensured by checking and reusing the 3-tuple for the Source IP/Port in the original direction.
- When the pool is exhausted of the 3-tuple assignments, the packets are dropped, else, they will be going out of the router they being 5-tuple unique (which is not intended).
- Passing fullcone option using iptables is part of …

Added support in the kernel for fullcone 3-tuple unique nat.

---

patch/driver-ixgbe-external-phy.patch
patch/series

This PR is patch for IXGBE.
0011-support-Broadcom-54616-Phy-for-Intel-igb-driver.patch is for IGB.
They are different code.
Do format with checkpatch.pl.
sonic-buildimage/src/sonic-linux-kernel/linux-4.9.168$ ./scripts/checkpatch.pl driver-ixgbe-external-phy.patch
total: 0 errors, 0 warnings, 0 checks, 37 lines checked

Add ixgbe driver patch to support BCM54616S_E_PHY phy

---

patch/fix_ismt_alignment_issue.patch
patch/series

Add linux patch to fix i2c ISMT 16-byte alignment issue of the DMA buffer address.

Fix i2c ISMT DMA buffer alignment issue

---

patch/driver-iommu-fix-amd-iommu-off.patch
patch/series

This change is to fix a kernel issue that we found when using buster kernel on Arista 7050s with amd_iommu=off.

Make amd iommu_disable safer

---

patch/0007-mlxsw-core-thermal-Set-default-thermal-trips-at-init.patch
patch/0008-mlxsw-qsfp_sysfs-Remove-obsolete-code-for-QSFP-EEPRO.patch
patch/0009-platform-mellanox-mlxreg-io-Add-support-for-compl.patch
patch/0010-platform-mellanox-mlxreg-hotplug-Add-environmental-d.patch
patch/series

What I did:
Added four patches along with hw-mgmt V.7.0000.3032 to buster. They are:
0007-mlxsw-core-thermal-Set-default-thermal-trips-at-init.patch
0008-mlxsw-qsfp_sysfs-Remove-obsolete-code-for-QSFP-EEPRO.patch
0009-platform-mellanox-mlxreg-io-Add-support-for-compl.patch
0010-platform-mellanox-mlxreg-hotplug-Add-environmental-d.patch
How I verify:
Run platform regression test on spectrum 1, spectrum 2 and specturm 3. No new issue found.

[Mellanox] Add new patches come along with hw-mgmt V.7.0000.3032 to buster

---

patch/0065-mlxsw-qsfp_sysfs-Remove-obsolete-code-for-QSFP-EEPRO.patch
patch/0066-platform-mellanox-mlxreg-hotplug-Add-environmental-d.patch
patch/series

**What I did:**
Added two patches come along with hw-mgmt V.7.0000.3034:
0058-mlxsw-qsfp_sysfs-Remove-obsolete-code-for-QSFP-EEPRO.patch
-	Remove QSFP EEPROM attribures from 'sysfs'.
0059-platform-mellanox-mlxreg-hotplug-Add-environmental-d.patch
-	Send "udev" event with environmental data in order to allow handling. "ENV{}" variables in "udev" rules.

[Mellanox] Add new patches come along with hw-mgmt V.7.0000.3034

---

patch/0011-mlxsw-core-thermal-Separate-temperature-trend-read-c.patch
patch/series

Why I did this?
Thermal algorithm not work on SN4700
How I fix?
Create a patch for linux kernel to treat temperature trend for ASIC, modules and gearboxed separately.
How I verify?
Manual test on SN4700.

[Mellanox] Fix issue: thermal algorithm not work on SN4700

---

patch/0067-mlxsw-core-thermal-Separate-temperature-trend-read-c.patch
patch/series

Why I did this?
Thermal algorithm not work on SN4700
How I fix?
Create a patch for linux kernel to treat temperature trend for ASIC, modules and gearboxed separately.
How I verify?
Manual test on SN4700.

[201911][Mellanox] Fix issue: thermal algorithm not work on SN4700

---

Makefile

1. generate .config files for armhf, arm64, amd64 in turn.
2. Compile the kernel with the corresponding environment variable.
3. rely on updates to the sonic-slave-buster, see PR https://github.com/Azure/sonic-buildimage/pull/4639.

fix kernel compile problem for arm64

---

Makefile

speed up kernel compile.
1. DO_DOCS=False do not skip generate document package on 4.19, use DEB_BUILD_PROFILES=nodoc instead.
2. use arch_amd64_none_amd64 to build the amd64 kernel package, avoid generating cloud-amd64 package.
As a result, jenkins pipeline linux-kernel-buster-build-pr job `#31` takes 1h 6min, compare to `#30` takes 1h 24min.
https://sonic-jenkins.westus2.cloudapp.azure.com/view/all/job/common/job/linux-kernel-buster-build-pr/

do not build DOCS and cloud-amd64

---

patch/0053-firmware-dmi-Add-access-to-the-SKU-ID-string-backpor.patch
patch/0063-platform-mellanox-mlxreg-io-Add-support-for-compl.patch
patch/0067-Add-support-for-new-transceivers-types-QSFP-DD-and-Q.patch
patch/0068-mlxsw-core-thermal-Separate-temperature-trend-read-c.patch
patch/0069-watchdog-mlx-wdt-support-new-watchdog-type-with-long.patch
patch/series

**1. Update existing patches:**
> - 0053-firmware-dmi-Add-access-to-the-SKU-ID-string-backpor.patch   
add one line which was missing during the rebase.
> - 0063-platform-mellanox-mlxreg-io-Add-support-for-compl.patch  
Add support for more registers.
> -  0067-mlxsw-core-thermal-Separate-temperature-trend-read-c.patch 
re-numbering it to  0068-mlxsw-core-thermal-Separate-temperature-trend-read-c.patch  and update the patch(the previous patch was rebased due to not applied in the correct sequence, now we correct the sequence and just take the original patch) 
**2. Add new patches with new hw-mgmt V.7.0010.1000** 
> - 0067-Add-support-for-new-transceivers-types-QSFP-DD-and-Q.patch 
to support QSFP-DD cable
> - 0069-watchdog-mlx-wdt-support-new-watchdog-type-with-long.patch  
to support new …

[Mellanox] Update existing patches and add new patches for 201911

---

patch/Support-for-fullcone-nat.patch
patch/series

Updated NAT kernel patch for 4.19 buster and enabled the "Support-for-fullcone-nat.patch" in series.
Depends on : https://github.com/Azure/sonic-buildimage/pull/4843
Signed-off-by: Akhilesh Samineni <akhilesh.samineni@broadcom.com>

Updated NAT kernel patch for 4.19 buster

---

patch/driver-hwmon-pmbus-dni_dps460-use-kstrtol-from-user.patch
patch/series

To avoid following kernel crash:
[   34.668610] Call Trace:
[   34.697843]  __mutex_add_waiter+0x23/0x50
[   34.745783]  __mutex_lock.isra.8+0x1d1/0x4a0
[   34.796846]  ? __handle_mm_fault+0xa83/0x1270
[   34.848948]  ? _kstrtoull+0x3b/0x90
[   34.890657]  set_target+0x95/0xf0 [dni_dps460]
[   34.943797]  kernfs_fop_write+0x116/0x190
[   34.991740]  vfs_write+0xa5/0x1a0
[   35.031363]  ksys_write+0x57/0xd0
[   35.070990]  do_syscall_64+0x53/0x110
[   35.114773]  entry_SYSCALL_64_after_hwframe+0x44/0xa9

use kstrtol_from_user in dni_dps460 driver

---

patch/net-psample-module-unload.patch
patch/series

Address https://github.com/Azure/sonic-linux-kernel/issues/153 by removing the __ro_after_init macro.
Checked that with this patch, it is possible to remove the module safely.

Issue #153 patch psample to safely unload the module

---

patch/kconfig-inclusions

This module is a bus arbitrator which allows 2 masters to manage the same bus.

Enable PCA9541 I2C mux module

---

patch/0001-hwmon-lm75-add-support-for-PCT2075.patch
patch/0004-dt-bindings-hwmon-Add-missing-documentation-for-lm75.patch
patch/0005-dt-bindings-hwmon-Add-tmp75b-to-lm75.txt.patch
patch/0006-device-tree-bindinds-add-NXP-PCT2075-as-compatible-d.patch
patch/series

New platform HW may use the NXP-PCT2075 thermal sensor which is compatible with
the lm75 sensor. These patches backport support for that sensor from 5.x
kernels.

hwmon-lm75: backport support for PCT2075 thermal sensor

---

patch/Support-for-fullcone-nat.patch

No functionality is changed. Only the format is changed, so it’s easier to apply to the Linux kernel source and to upstream it.

Improve netfilter fullclone nat support patch

---

patch/series

all internal patches will be add below the marker. This eases
internal patch management when public patches change

add internal patch marker

---

patch/macsec-Netlink-support-of-XPN-cipher-suites-IEEE-802.patch
patch/macsec-Support-XPN-frame-handling-IEEE-802.1AEbw.patch
patch/netlink-add-NLA_MIN_LEN.patch
patch/series

back following three patches to 4.19 to support macsec xpn
21ecf0e03: macsec: Support XPN frame handling - IEEE 802.1AEbw (in v5.7-rc1)
48ef50fa8: macsec: Netlink support of XPN cipher suites (IEEE 802.1AEbw) (in v5.7-rc1)
6f455f5f4: netlink: add NLA_MIN_LEN (in v5.2-rc1)

backport macsec xpn support to 4.19 kernel

---

patch/0022-mlxsw-core-Increase-critical-threshold-for-ASIC-ther.patch
patch/0023-mlxsw-core-Add-validation-of-transceiver-temperature.patch
patch/series

Backport new patches to increase the ASIC critical threshold from 110C to 140C, and validate the transceiver critical threshold temperature:
1. 0022-mlxsw-core-Increase-critical-threshold-for-ASIC-ther.patch   https://github.com/torvalds/linux/commit/b06ca3d5a43ca2dd806f7688a17e8e7e0619a80a
2. 0023-mlxsw-core-Add-validation-of-transceiver-temperature.patch  https://github.com/torvalds/linux/commit/57726ebe2733891c9f59105eff028735f73d05fb
This change has been verified on all Mellanox devices based on Spectrum-1, Spectrum-2, and Spectrum-3 ASIC

Backport patches to increase critical threshold for ASIC and validate transceiver temperature

---

patch/0070-mlxsw-core-Increase-critical-threshold-for-ASIC-ther.patch
patch/0071-mlxsw-core-Add-validation-of-transceiver-temperature.patch
patch/series

Backport new patches to increase the ASIC critical threshold from 110C to 140C, and validate the transceiver critical threshold temperature:
1. 0070-mlxsw-core-Increase-critical-threshold-for-ASIC-ther.patch   https://github.com/torvalds/linux/commit/b06ca3d5a43ca2dd806f7688a17e8e7e0619a80a
2. 0071-mlxsw-core-Add-validation-of-transceiver-temperature.patch  https://github.com/torvalds/linux/commit/57726ebe2733891c9f59105eff028735f73d05fb
This change has been verified on all Mellanox devices based on Spectrum-1, Spectrum-2, and Spectrum-3 ASIC.

[201911] Backport patches to increase critical threshold for ASIC and validate transceiver temperature

---

patch/driver-i2c-mux-pca954x-allow-management-of-device-idle-stat.patch
patch/driver-i2c-mux-pca954x-remove-support-for-unused-platform-d.patch
patch/driver-pca954x-i2c-mux-force-deselect-on-exit-flag.patch
patch/series

f1fb64b04b: driver-i2c-mux-pca954x-allow-management-of-device-idle-stat.patch (v5.2-rc1)
ddd7c492d: i2c: mux: pca954x: remove support for unused platform data (v5.2-rc1)
tested on celestica dx010

[backport]: i2c: mux: pca954x: allow management of device idle state via sysfs

---

.azure-pipelines/build-template.yml
azure-pipelines.yml

[ci]: build amd64/armhf/arm64

---

patch/0024-mlxsw-core-Fix-memory-leak-on-module-removal.patch
patch/0025-platform-x86-mlx-platform-Remove-PSU-EEPROM-configur.patch
patch/0026-platform-x86-mlx-platform-Remove-PSU-EEPROM-configur.patch
patch/series

0024-mlxsw-core-Fix-memory-leak-on-module-removal.patch https://github.com/torvalds/linux/commit/adc80b6cfedff6dad8b93d46a5ea2775fd5af9ec  @v5.10-rc2
0025-platform-x86-mlx-platform-Remove-PSU-EEPROM-configur.patch  https://github.com/torvalds/linux/commit/2bf5046bdb649908df8bcc0a012c56eee931a9af @v5.11-rc1
0026-platform-x86-mlx-platform-Remove-PSU-EEPROM-configur.patch  https://github.com/torvalds/linux/commit/912b341585e302ee44fc5a2733f7bcf505e2c86f @v5.11-rc1
regression tests have been performed against these patches on the Mellanox platform, no issue found.
Signed-off-by: Kebo Liu <kebol@nvidia.com>

Backport new kernel patches

---

patch/driver-hwmon-pmbus-dni_dps460-add-status-attributes.patch
patch/series

Signed-off-by: Arun Saravanan Balachandran <Arun_Saravanan_Balac@dell.com>
Add attributes to retrieve PMBus status command codes
(Port of #194 from 201811 branch)

[dni_dps460] Add attributes to retrieve PMBus status command codes

---

patch/kconfig-exclusions

Fix Azure/sonic-buildimage#6866
Unset CONFIG_THERMAL_STATISTICS.
Reason:
Kernel thermal zones binding to the cooling device together with CONFIG_THERMAL_STATISTICS=y causes kernel crash as out of boundary:
trans_table is two-dimensional table allocated per max cooling state (10).
If statistics is configured, thermal_cooling_device_stats_update() will be called and will try to update out of boundary:
stats->trans_table[stats->state * stats->max_states + new_state]++
Kernel crash with the following stack trace:
```
[  269.474092] watchdog: watchdog1: watchdog did not stop!
[  269.533625] list_del corruption. prev->next should be ffff9e136bd57418, but was 677ac660ffffffff
[  269.543482] kernel BUG at lib/list_debug.c:53!
[  269.548458] invalid opcode: 0000 [#1] SMP PTI
[  269.553326] CPU: 1 …
```

Unset CONFIG_THERMAL_STATISTICS to prevent kernel crash

---

patch/0072-mlxsw-core-Remove-critical-trip-point-from-thermal-z.patch
patch/series

Backport a patch to remove critical trip point from thermal zones for Mellanox devices
1. 0072-mlxsw-core-Remove-critical-trip-point-from-thermal-z.patch
It has been verified on Mellanox devices
Signed-off-by: Stephen Sun <stephens@nvidia.com>

Backport patch to remove critical trip point from thermal zones

---

patch/0027-mlxsw-core-Remove-critical-trip-point-from-thermal-z.patch
patch/series

Backport a patch to remove critical trip point from thermal zones for Mellanox devices
1. 0027-mlxsw-core-Remove-critical-trip-point-from-thermal-z.patch
```
Disable software thermal protection by removing critical trip points
for the all thermal zones.
According to the system requirements software should never perform
system thermal protection, since all the systems implement two levels
of thermal protection: the first one is performed by firmware, the
second, in case firmware was not able to perform protection, by
hardware, while the temperature threshold for hardware protection is
higher than for firmware.
In both cases, when critical temperature is reached, system will be
shutdown.
Signed-off-by: Vadim Pasternak <vadimp@nvidia.com>
```
It has been verified on Mellanox devices …

[Mellanox] Backport patch to remove critical trip point from thermal zones

---

patch/cisco-hwmon-pmbus_core-pec-support-check.patch

support it
Added code to check if i2c bus has capability to support PEC [ Packet Error Correction ] and enable it only if both controller and bus support PEC
I2C_FUNC_SMBUS_PEC can be used to check PEC capability
Signed-off-by: Madhava Reddy Siddareddygari <msiddare@cisco.com>

hwmon: (pmbus_core) Do not enable PEC if adapter doesn't

---

patch/armhf_secondary_boot_online.patch
patch/series

On continuous reboot, once in a while CPU1 (secondary cpu) doesn't come online. Issue seen on migrating to Debian gcc 8.3.6 from gcc7.
Until introducing the Debian GCC 8.x version – the execution process didn’t influence
mmu intialization before starting the socondary processor.
The new GCC version makes some optimizations that execute the SW faster and once in a while,
causing the Secondary CORE to start while the MMU is still in the initialization stage.
Once adding a slight delay right after the MMU initialization –
compensate the optimized code and enables the MMU to init successfully before the 2nd CORE starts.
Signed-off-by: Rajkumar Pennadam Ramamoorthy <rpennadamram@marvell.com>

[Marvell] CPU1 failure on continuous reboot

---

patch/driver-support-optoe-write-max.patch
patch/series

In current optoe driver, the value of write_max is hardcoded to one byte.
CMIS spec supports firmware upgrade on QSFP-DD transceivers which means there is significant overhead due to this one byte write limit when a platform wants to upgrade the firmware over an i2c bus at 100Khz.
The overhead is more pronounced when a platform has shared master and platform needs to perform firmware upgrade on multiple transceivers
Signed-off-by: Prince George <prgeor@microsoft.com>

Increase optoe's write-max to support i2c block write

---

patch/0033-i2c-mlxcpld-Update-module-license.patch
patch/0034-i2c-mlxcpld-Add-support-for-I2C-bus-frequency-settin.patch
patch/0035-i2c-mux-mlxcpld-Update-module-license.patch
patch/0036-i2c-mux-mlxcpld-Move-header-file-out-of-x86-realm.patch
patch/0037-platform-x86-mlxcpld-Update-module-license.patch
patch/0038-i2c-mux-mlxcpld-Convert-driver-to-platform-driver.patch
patch/0039-i2c-mux-mlxcpld-Prepare-mux-selection-infrastructure.patch
patch/0040-i2c-mux-mlxcpld-Get-rid-of-adapter-numbers-enforceme.patch
patch/0041-i2c-mux-mlxcpld-Extend-driver-to-support-word-addres.patch
patch/0042-i2c-mux-mlxcpld-Extend-supported-mux-number.patch
patch/0043-i2c-mux-mlxcpld-Add-callback-to-notify-mux-creation-.patch
patch/0044-platform-x86-mlx-platform-remove-an-unused-variable.patch
patch/0045-platform-x86-mlx-platform-Fix-item-counter-assignmen.patch
patch/0046-platform-x86-mlx-platform-Fix-item-counter-assignmen.patch
patch/0047-mlxsw-core-Set-thermal-zone-polling-delay-argument-t.patch
patch/0048-mlxsw-reg-Extend-MTMP-register-with-new-threshold-fi.patch
patch/0049-mlxsw-core_env-Read-module-temperature-thresholds-us.patch
patch/0050-mlxsw-thermal-Add-function-for-reading-module-temper.patch
patch/0051-mlxsw-thermal-Read-module-temperature-thresholds-usi.patch
patch/series

Backport kernel patches come along with Mellanox hw-mgmt package release V.7.0010.3134:
V5.14-rc1 includes all following patches.
| Patch name                                     |  Commit hash                                                    |                                                                                                
| -----------------------------------------------------| ------------------------------------------------------------------------------------------ |
|0033-i2c-mlxcpld-Update-module-license.patch | https://github.com/torvalds/linux/commit/f069291bd5fcb85c6eb53f9b1ab23bcfcaad93f2 |
|0034-i2c-mlxcpld-Add-support-for-I2C-bus-frequency-settin.patch | https://github.com/torvalds/linux/commit/66b0c2846ba8de569026a067bb5a34ea5768408c | …

[Mellanox] Backport kernel patches coming along with Mellanox hw-mgmt package release V.7.0010.3134

---

patch/driver-support-optoe-twoaddr-a2h-access.patch
patch/series

Enable 0x51 (A2h) access for optoe2 even when DDM is unsupported, for
accessing vendor specific fields. Some SFP optics that do not support DDM
can have vendor specific implementation via 0x51 in A2h register space
(eg. Mailbox Registers).
Removed the DDM support check for optoe2 (TWO_ADDR) and now its EEPROM
size is 512 bytes minimum. Return error when accessing beyond 256 bytes
for optics that do not support I2C address 0x51.

Enable A2h access for optoe2 even when DDM is unsupported

---

patch/cisco-npu-disable-other-bars.patch
patch/series

For Cisco ASIC only BAR0 is valid. Not disabling other BAR's
was resulting in pci_enable_device function failure in P0
Pacific ASIC's. Further debugging and consultion with Hardware
team, issue seems to be related to only P0 version of ASIC and
workaround suggested is to disable unused PCI BAR.
This is same pull request reviewed ealier,
https://github.com/Azure/sonic-linux-kernel/pull/225/
Cisco experimented removing this patch, but identified that
there are boards in the field with Pacific ASIC.
This patch is needed for these ASIC's to work, hence re-submitting.
NPU is commonly used name for the packet forwarding ASIC's.
Signed-off-by: Madhava Reddy Siddareddygari <msiddare@cisco.com>

NPU disabled used PCIe BAR

---

patch/cisco-hwmon-pmbus_core-pec-support-check.patch
patch/series

Ported hwmon: (pmbus_core) Check adapter PEC support patch to 5.10.40 kernel.
When switch from Linux 4.19.x to 5.10.40 the patch was disabled, as it did not apply cleanly. Forward port it to Linux 5.10.40 and add it to the Linux 5.10 patch series.
Test on cisco-8000 platform
root@localhost:/home/cisco# show plat temp
Sensor Temperature High TH Low TH Crit High TH Crit Low TH Warning Timestamp
CPU_U17_P1P05V_TEMP 35.187 125 -5 135 -10 False 20211011 13:57:45
CPU_U17_PVCCIN_TEMP 34.937 125 -5 135 -10 False 20211011 13:57:45
CPU_U117_P1P2V_TEMP 30.75 125 -5 135 -10 False 20211011 13:57:46
CPU_U117_P1P05V_TEMP 31 125 -5 135 -10 False 20211011 13:57:46
DIMM_TEMP1 28.25 125 -5 135 -10 False 20211011 13:57:47
FAN_Sensor 32.375 97 -5 102 -10 False 20211011 13:57:45
MB_3_3V_L_TEMP_L1 33.187 125 -5 …

Ported hwmon: (pmbus_core) Check adapter PEC support patch to 5.10.40 kernel

---

patch/driver-arista-mmc-drive-strength.patch
patch/driver-arista-mmc-not-working-on-AMD-platforms.patch
patch/driver-arista-mmc-restrict-eMMC-drive-to-50Mhz-from-cmdline.patch
patch/linux-4.11-mmc-sdhci-pci-Add-support-for-HS200-tuning-mode-on-AMD.patch
patch/series

[201811] Apply kernel patches to fix emmc unreliability

---

patch/config-log-buf-len-increase.patch
patch/series

This increase allows for more logs to be stored in the kernel log buffer.
The default was 128k which this config change bumps to 1M.
It can prove useful in cases where /var/log becomes un-writtable.

[201811] Increase log_buf_len size to 1M

---

patch/driver-arista-mmc-drive-strength.patch
patch/driver-arista-mmc-not-working-on-AMD-platforms.patch
patch/driver-arista-mmc-restrict-eMMC-drive-to-50Mhz-from-cmdline.patch
patch/linux-4.11-mmc-sdhci-pci-Add-support-for-HS200-tuning-mode-on-AMD.patch
patch/series

[201911] Apply kernel patches to fix emmc unreliability

---

patch/config-log-buf-len-increase.patch
patch/series

This increase allows for more logs to be stored in the kernel log buffer.
The default was 128k which this config change bumps to 1M.
It can prove useful in cases where /var/log becomes un-writtable.

[201911] Increase log buf len size to 1M

---

patch/driver-arista-mmcblk-not-working-on-AMD-platforms.patch
patch/driver-arista-restrict-eMMC-drive-to-50Mhz-from-userland.patch
patch/series

[202012] Apply kernel patches to fix emmc unreliability

---

patch/kconfig-inclusions

This increase allows for more logs to be stored in the kernel log buffer.
The default was 128k which this config change bumps to 1M.
It can prove useful in cases where /var/log becomes un-writtable.

[202012] Increase log_buf_len to 1M for all architecture

---

patch/kconfig-inclusions

This increase allows for more logs to be stored in the kernel log buffer.
The default was 128k which this config change bumps to 1M.
It can prove useful in cases where /var/log becomes un-writtable.

Increase log_buf_len to 1M on all architectures

---

patch/cisco-x86-gpio-config.patch
patch/series

In the 202012 branch, there is a config option committed to set the
number of GPIOs on the system to 10240, because some Cisco hardware
could have that many GPIOs. This config option is, for whatever reason,
not on the master branch.
Therefore, re-add cisco-x86-gpio-config.patch, but reduce it to the
parts that allow configuration of the config.
Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>

Re-add certain parts of cisco-x86-gpio-config.patch

---

patch/0064-platform-mellanox-mlxreg-io-Fix-read-access-of-n-byt.patch
patch/0144-platform-x86-mlx-platform-Fix-cpld-_pn-register-seco.patch
patch/series

These patches are being back-ported from the linux mainline in order to fix a bug where all bytes of CPLD registers are not being fully read by the kernel on Mellanox platforms in 4.19
See table below for upstream commits
| Patch                                                           | Upstream                                                                        | 
|-----------------------------------------------------------------|---------------------------------------------------------------------------------|
| 0064-platform-mellanox-mlxreg-io-Fix-read-access-of-n-byt.patch | https://github.com/gregkh/linux/commit/5fd56f11838da1580cc77743c08cf02c9cd48380 | 
| 0144-platform-x86-mlx-platform-Fix-cpld-_pn-register-seco.patch | …

[202012] Add upstreamed patches which backport support for registers for CPLD PNs

---

patch/0169-TMP-mlxsw-i2c-Prevent-transaction-execution-for-spec.patch
patch/0169-mlxsw-i2c-Prevent-transaction-execution-for-spec.patch
patch/series

Signed-off-by: Kebo Liu <kebol@nvidia.com>
This is to backport the patch from PR: https://github.com/Azure/sonic-linux-kernel/pull/279 to 202111 branch
Do not run transaction in cases chip is in reset or in-filed update states.
This patch fixes an issue encountered during SONiC warm-reboot: during
ISSU start the kernel reports that CPU stall is detected:
`INFO: rcu_sched detected stalls on CPUs/tasks`
This patch won't be upstreamed due to the upstream driver not supporting
ISSU.

[202111][patch] mlxsw: i2c: Prevent transaction execution for special chip states

---

patch/0065-TMP-mlxsw-i2c-Prevent-transaction-execution-for.patch
patch/0065-mlxsw-i2c-Prevent-transaction-execution-for.patch
patch/series

… chip
states
Do not run transaction in cases chip is in reset or in-filed update states.
This patch fixes an issue encountered during SONiC warm-reboot: during
ISSU start the kernel reports that CPU stall is detected:
```
INFO: rcu_sched detected stalls on CPUs/tasks
```
This patch won't be upstreamed due to the upstream driver not supporting
ISSU.
Signed-off-by: Stepan Blyschak <stepanb@nvidia.com>

[202012][patch] mlxsw: i2c: Prevent transaction execution for special

---

patch/0153-platform-mellanox-Add-config3-register-support.patch
patch/series

Signed-off-by: Kebo Liu <kebol@nvidia.com>
Add a new patch comes with the hw-mgmt version V.7.0010.2348
`Add config3 register which is used to get COMEX CPU board version`
Currently, this patch is under work: https://patchwork.kernel.org/project/platform-driver-x86/patch/20220711084559.62447-7-vadimp@nvidia.com/
when backporting to 202012 branch (kernel version 4.19), the patch was reshaped accordingly.

[202012]Add config3 register which is used to get COMEX CPU board version

---

patch/0001-net-ipv6-Introduce-accept_unsolicited_na-knob-to-imp.patch
patch/0002-net-ipv6-Expand-and-rename-accept_unsolicited_na-to-.patch
patch/series

Backport following commits to 4.19 kernel:
- https://github.com/torvalds/linux/commit/f9a2fb73318eb4dbf8cd84866b8b0dd012d8b116
- https://github.com/torvalds/linux/commit/3e0b8f529c10037ae0b369fc892e524eae5a5485
These commits allow the kernel to create new IPv6 neighbor entries when receiving neighbor advertisement messages for IPs that don't already exist in the neighbor cache
Signed-off-by: Lawrence Lee <lawlee@microsoft.com>

[patch]: Add accept_untracked_na kernel param

---

patch/0001-net-arp-introduce-arp_evict_nocarrier-sysctl-paramet.patch
patch/series

This PR is to backport the following commits to kernel v5.10:
https://github.com/torvalds/linux/commit/fcdb44d08a95003c3d040aecdee286156ec6f34e
The commit above is to introduce a new sysctl parameter `arp_evict_no_carrier`.
Fixes: https://github.com/sonic-net/sonic-buildimage/issues/11924
Signed-off-by: Longxiang Lyu <lolv@microsoft.com>

[patch]: Introduce sysctl param `arp_evict_no_carrier`

---

patch/driver-arista-mmcblk-not-working-on-AMD-platforms.patch
patch/driver-arista-restrict-eMMC-drive-to-50Mhz-from-userland.patch
patch/series

[202205] Fix some emmc unreliability seen on older AMD CPUs

---

Makefile

Dependent PR: https://github.com/sonic-net/sonic-buildimage/pull/12428
Can be merged in any order

Update Makefile to provision the ability of building with non-upstream patches

---

manage-config

Fix setting a config value in kconfig-inclusions when there's already a conflicting existing value in defconfig.
For example, trying to overwrite `CONFIG_SYSTEM_TRUSTED_KEYS` would have no effect, because there's already a value specified in the file, and the existing value takes precedence.
Also support verifying the value of strings (and not just y/m/n settings). `CONFIG_SYSTEM_TRUSTED_KEYS` takes a string value, and the current code doesn't completely handle strings.
Fixes #299.
Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>

Fix setting a config with an already-existing conflicting value

---

patch/driver-arista-mmcblk-not-working-on-AMD-platforms.patch
patch/driver-arista-restrict-eMMC-drive-to-50Mhz-from-userland.patch
patch/series

Fix some emmc unreliability seen on older AMD CPUs

---

patch/0001-hwmon-emc2305-Fix-unable-to-probe-emc2301-2-3.patch
patch/series

The current code only supports EMC2305, enable support for EMC2301/2/3 also
Same driver is used for EMC 2301/2/3/5 family of products. 
https://docs.kernel.org/hwmon/emc2305.html
The definitions of 'EMC2305_REG_PRODUCT_ID' and 'EMC2305_REG_DEVICE' are
both '0xfd', they actually return the same value, but the values returned
by emc2301/2/3/5 are different, so probe emc2301/2/3 will fail, This patch
fixes that.
upstream commit:
https://github.com/torvalds/linux/commit/4d50591ebf60ccf79380fff3a4c23659c61c482f
Signed-off-by: Natarajan Subbiramani <natarajan.subbiramani.ext@nokia.com>
Signed-off-by: Xingjiang Qiao <nanpuyue@gmail.com>
Link: https://lore.kernel.org/r/20221206055331.170459-1-nanpuyue@gmail.com
Fixes: 0d8400c ("hwmon: (emc2305) add support for EMC2301/2/3/5 RPM-based PWM Fan …

Fix unable to probe emc2301/2/3

---

Makefile

Currently, non upstream patches are applied only after upstream patches. 
**What i Did**
1) Apply a patch to the series files and copy the relevant patches into the patch/ folder
2) Non upstream Patches that reside in the sonic repo will not be saved in a tar file bur rather in a folder pointed out by `EXTERNAL_KERNEL_PATCH_LOC`. The build variable name is also updated to `INCLUDE_EXTERNAL_PATCHES` 
3) `INCLUDE_EXTERNAL_PATCHES` will be a mandatory parameter to include NON_UPSTREAM_PATCHES

Provision the ability to apply the non upstream patches in any order

---

Makefile
manage-config

The name SECURE_UPGRADE_DEV_SIGNING_CERT is misleading, this flag is relevant to both to dev and prod signing.
Rename all mentions of name SECURE_UPGRADE_DEV_SIGNING_CERT to SECURE_UPGRADE_SIGNING_CERT - this is also done with PR in sonic-buildimage repository - https://github.com/sonic-net/sonic-buildimage/pull/14591

Rename SECURE_UPGRADE_DEV_SIGNING_CERT to SECURE_UPGRADE_SIGNING_CERT

---

patch/0021-arm64-dts-marvell-Add-Nokia-7215-IXS-A1-board.patch
patch/series

Create platform specific dts for marvell -arm64 based Nokia 7215-IXS-A1 platform
This dts is derived from Marvell RD-AC5X board.
differences between RD-AC5X and 7215-A1 is only the default LED setting for Mangement port.

arm64: dts: marvell: Add Nokia 7215-IXS-A1 board

---

CODEOWNERS
README.md

Update the `CODEOWNERS` file to point to the current sonic-linux-kernel maintainers team. In addition, update the build badges in `README.md` to show the current build status.
In a future PR, I might add per-architecture build badges.

Update codeowner and build info

---

patch/0001-net-allow-user-to-set-metric-on-default-route-learne.patch
patch/series

What I did:
Patch taken from Linux 5.12 to allow user to set metric on default route learned via Router Adv message for IPv6
This PR is to backport the following commits to kernel v5.10:
https://github.com/torvalds/linux/commit/6b2e04bc240fe9be9e690059f710e9f95346d34d
ADO: 24888962
Why I did:
Fixes: https://github.com/sonic-net/sonic-buildimage/issues/16209

[PATCH] net: allow user to set metric on default route learned via  Router Advertisement

---

patch/0001-Change-the-system.map-file-permission-only-readable-.patch
patch/series

Change the system.map file permission only readable by root

Change the system.map file permission only readable by root

---

patch/0176-platform-mellanox-fix-reset_pwr_converter_fail-attri.patch
patch/0177-Documentation-ABI-fix-description-of-fix-reset_pwr_c.patch
patch/0178-platform-mellanox-Introduce-support-for-next-generat.patch
patch/0285-platform-mellanox-nvsw-sn2201-change-fans-i2c-busses.patch
patch/series

- 0176-platform-mellanox-fix-reset_pwr_converter_fail-attri.patch : https://github.com/torvalds/linux/commit/488f0fca0db0
- 0177-Documentation-ABI-fix-description-of-fix-reset_pwr_c.patch : https://github.com/torvalds/linux/commit/e7210563432a
- 0178-platform-mellanox-Introduce-support-for-next-generat.patch : https://github.com/torvalds/linux/commit/fcf3790b9b63
- 0285-platform-mellanox-nvsw-sn2201-change-fans-i2c-busses.patch: https://github.com/torvalds/linux/commit/e2aabb7cd4dd145c07d6a66407b01c635710849e

[202205] [Mellanox] Add patch for hw-mgmt 7.0020.4305

---

patch/Support-for-fullcone-nat.patch
patch/series

Fullcone NAT changes are ported from 5.10 to 6.1 kernel.
Signed-off-by:  Akhilesh Samineni <akhilesh.samineni@broadcom.com>

Ported Fullcone NAT changes are ported from 5.10 to 6.1 kernel.

---

patch/0012-net-mvpp2-clear-BM-pool-before-initialization.patch
patch/series

This change fixes the kernel panic during warm-restart kexec reload.
upstream commit in Linux netdev: https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net.git/commit/drivers/net/ethernet/marvell?id=9f538b415db862e74b8c5d3abbccfc1b2b6caa38

[Marvell-arm64] Fix kexec kernel panic in mvpp2

---

patch/0021-arm64-dts-marvell-Add-Nokia-7215-IXS-A1-board.patch

Create platform specific DTS for Marvell-arm64 based Nokia 7215-IXS-A1 platform.
7215-IXS-A1 is an aggregation switch based on Marvell AlleyCat5X. This DTS is extracted from Marvell cn9130-crb (reference board) and removed unused nodes along with platform specific changes.
This PR is a backport for PR #378 due to difference in patch file number between 5.10 and 6.1
Upstream Kernel PR
https://lore.kernel.org/linux-arm-kernel/CAJOx763HwgK-EEt-AkVqtoObhx_VGokj-Mn0yhS7Sno0uDOZfw@mail.gmail.com/T/#m3d1fc5bce0dcb5ec001f8496a207ccb485903507

arm64: dts: marvell: Add DTS for 7215-IXS-A1 board

---

patch/driver-support-optoe-dynamic-write-timeout.patch
patch/series

Cherry-pick for https://github.com/sonic-net/sonic-linux-kernel/pull/370
The optoe kernel driver currently has a fixed 25ms write timeout value. We need to provide an interface to support overwriting the write_timeout value from userspace.
The overwriting of the write timeout value is needed for some non-standard optics which are not compliant with the timeout value in spec and will help in resolving issues related to EEPROM access.
The overwriting of the write_timeout value can be done based on platform or vendor of the transceiver.
Following sysfs will be created with this change
```
/sys/bus/i2c/devices/<bus_id>-0050/write_timeout
```
Testing
```
root@sonic:/sys/bus/i2c/devices/31-0050# ls
dev_class  driver  eeprom  modalias  name  port_name  power  subsystem  uevent  write_max …
```

[202311] Dynamic write timeout support for optoe driver

---

.azure-pipelines/build-template.yml

The current reference build 426041 is deleted and thus the pipeline fails. 
In future, we need to update the approach to use the latest build from the corresponding branch

Update reference build to be used for kconfig diff

---

patch/0015-arm64-dts-marvell-Add-Supermicro-SSE-G3748-board.patch
patch/series

This patch adds support SONiC Linux Kernel DTS file for Supermicro 1G switch SSE-G3748.
The DTS file is derived from Marvell RD-AC5X reference board  dts file ac5-98dx35xx-rd.dts.
SPI flash partition and i2c1 device configuration are modified to meet SSE-G3748 hardware design.
Testing:
1. Tested running M0/PTF32 test suites for this new platform.
2. Verified image partitions
3. Verified uboot and sonic platform functionalities

Add patch of SONiC Linux kernel DTS file to support Supermicro SSE-G3748 1G switch

---

Makefile

1) Rename the make variable `SOURCE_FILE_BASE_URL` to `LINUX_SOURCE_BASE_URL`
2) Remove the deprecated code to download compiled linux kernel artifacts

Remove compiled artifact download and rename base url

---

patch/driver-support-optoe-write-max_fix.patch
patch/series

Optoe driver with write-max > 1 when using the i2c message buffer was allocating only 3(1+2) bytes  which means while copying the user data for i2c adapters supporting the native i2c functions will overwrite the message buffer size. This will not happen for i2c adapters that does not support native i2c functions like pure SMBUS controller.

Fix optoe's write_max when adapter supports i2c functions

---

patch/driver-support-optoe-write-max_fix.patch
patch/series

202311 Cherry-pick for https://github.com/sonic-net/sonic-linux-kernel/pull/407
Optoe driver with write-max > 1 when using the i2c message buffer was allocating only 3(1+2) bytes which means while copying the user data for i2c adapters supporting the native i2c functions will overwrite the message buffer size. This will not happen for i2c adapters that does not support native i2c functions like pure SMBUS controller.

[202311] [optoe] Fix optoe's write_max when using native i2c driver

---

patch/driver-support-optoe-write-max_fix.patch
patch/series

202405 cherry-pick for PR https://github.com/sonic-net/sonic-linux-kernel/pull/407
Optoe driver with write-max > 1 when using the i2c message buffer was allocating only 3(1+2) bytes which means while copying the user data for i2c adapters supporting the native i2c functions will overwrite the message buffer size. This will not happen for i2c adapters that does not support native i2c functions like pure SMBUS controller.

[202405] [optoe] Fix optoe's write_max when using native i2c driver

---

patch/driver-net-tg3-change-dma-mask-for-57766.patch
patch/series

Cherry-picking #421 
* Add kernel patch to fix 57766 staying down after reset
This is the workaround for incorrected detected DMA overflow that may result in NIC staying down after reset. The fix is to limit address space that can be used.
* Add description and fix bookworm build
* Fix subject in the patch
* Fix patch/series conflict during cherry-pick
---------

tg3: fix broadcom NIC 57766 staying down issue (#421)

---

patch/driver-hwmon-pmbus-dni_dps460-update-to-5-10.patch
patch/series

The dps460 driver has included a copy of `struct pmbus_data` within its code (which is bad for many reasons). Because of this, it hasn't been updated since the 4.19 version of `struct pmbus_data` (since there wouldn't have been any compilation errors), and now differs from the actual structure definition, resulting in eventual kernel panics.
As a quick fix, update `struct pmbus_data` that is present in dps460 to the current version.
Sample kernel panic:
```
[161211.582193] BUG: unable to handle page fault for address: 00000000000348e0
[161211.665585] #PF: supervisor write access in kernel mode
[161211.729234] #PF: error_code(0x0002) - not-present page
[161211.791844] PGD 1d42dd067 P4D 1d42dd067 PUD 1d42dc067 PMD 0
[161211.860693] Oops: 0002 [#1] SMP NOPTI
[161211.905628] CPU: 1 PID: 6768 …
```

[202305] Fix the dps460 kernel driver for the 5.10 kernel

---

patch/0001-devlink-Fix-RCU-stall-when-unregistering-a-devlink-i.patch
patch/series

Resolves: https://github.com/sonic-net/sonic-buildimage/issues/20368
Ref: https://lore.kernel.org/stable/20241001112035.973187-1-idosch@nvidia.com/t/#u
> But first of, why? Why not just take the upstrema commits instead?
> 
> thanks,
> greg k-h
Ido:
> There were a lot of changes as part of the 6.3 cycle to completely
> rework the semantics of the devlink instance reference count. As part of
> these changes, commit d77278196441 ("devlink: bump the instance index
> directly when iterating") inadvertently fixed the bug mentioned in this
> patch. This commit cannot be applied to 6.1.y as-is because a prior
> commit (also in 6.3) moved the code to a different file (leftover.c ->
> core.c). There might be more dependencies that I'm currently unaware of.
> 
> The alternative, proposed in this …

Fix RCU stall detected in kernel 6.1 when unregistering devlink

---

patch/0001-Revert-mtd-spi-nor-Correct-flags-for-Winbond-w25q128.patch
patch/series

Backport https://github.com/sonic-net/sonic-linux-kernel/pull/436 to 202405

[202405] Fix for Winbond flash devices that could not parse SFDP

---

patch/kconfig-exclusions

Under some specific circumstances, having memory encryption turned on lead to silent kernel crashes.
This is currently preventing SONiC using linux 6.1+ from being kexec'ed from Aboot uing kexec-tools in 64 bit.
Bisecting the kernel code pointed the following change as the culprit
[c01fce9cef8491974f7f007f90281f1608400768] x86/compressed: Add SEV-SNP feature detection/setup

Disable AMD memory encryption

---

patch/revert-456d8aa-to-fix-pcie_aspm_exit_link_status.patch
patch/series

Fixing: https://github.com/sonic-net/sonic-buildimage/issues/20901
Reverting: https://github.com/torvalds/linux/commit/456d8aa37d0f56fc9e985e812496e861dcd6f2f2
After the 6.1.94 kernel bump up https://github.com/torvalds/linux/commit/456d8aa37d0f56fc9e985e812496e861dcd6f2f2 was absorbed.
This change can cause kernel panics during reboot.
The correct fix/solution is still under discussion so for now working around this by reverting the commit
Here is a snippet of the kernel panic (full logs can be found in the issue referenced above):
```
2024 Nov 14 23:21:46.345708 str2-7804-sup-1 WARNING kernel: [ 1286.839869] general protection fault, probably for non-canonical address 0x32b727d667b7999a: 0000 [#1] PREEMPT SMP PTI
2024 Nov 14 23:21:51.054518 str2-7804-sup-1 WARNING kernel: [ 1286.968107] …
```

[PCI/ASPM] Revert commit `456d8aa` to avoid kernel panics in `6.1.94`

---

patch/revert-456d8aa-to-fix-pcie_aspm_exit_link_status.patch
patch/series

Manual cherry-pick of https://github.com/sonic-net/sonic-linux-kernel/pull/448 to the 202405 branch.
* Reverting 456d8aa to avoid kernel panics in 6.1.94
For certain pci tree structures involving pci devices with sibling functions we can get a nullptr dereference when the link state goes down due to this change.
Fixing: https://github.com/sonic-net/sonic-buildimage/issues/20901 
Reverting: https://github.com/torvalds/linux/commit/456d8aa37d0f56fc9e985e812496e861dcd6f2f2 
Upstream Discussion: https://lore.kernel.org/linux-pci/20240801171103.GA107989@bhelgaas/T/#t
* Adding upstream discussion link and summary in patch

[202405][PCI/ASPM] Revert commit `456d8aa` to avoid kernel panics in `6.1.94`

---

patch/driver-support-optoe-non-sfp-reset-page-select.patch
patch/series

**Description**
The optoe kernel driver currently assumes that the page select byte (page 0, byte 127) is set to 0h before accessing the upper memory on page 0h.
This assumption causes failures when accessing the module's EEPROM in multiple scenarios.
On the contrary, the driver currently sets the page select byte if the intended page to be accessed is > 0 as evident from the below code
https://github.com/opencomputeproject/oom/blob/c32499a89dff005e7ff2acb48b33f55543ce5140/optoe/optoe.c#L344-L353
**Impact**
If the optoe driver accesses any page except page 0h and the code for restoring the page select byte to 0h fails, subsequent attempts to
access the upper memory of page 0h will fail because the page select byte from the previous transaction remains unchanged. …

[optoe] Reset page select byte to 0 before upper memory access on page 0h

---

patch/0001-efi-memattr-Ignore-table-if-the-size-is-clearly-bogus.patch
patch/series

Backport https://github.com/torvalds/linux/commit/8fbe4c49c0ccac9a6a3cff35a45fa55d4ae35d6e into sonic kernel.
On one of our platforms, we sporadically seeing this kernel error log after a reboot
```
2025 Jul  8 15:05:16.109392 sonic ERR kernel: [    0.121956] efi: memattr: Failed to map EFI Memory Attributes table @ 0xb4ad7118
```
This error log is hard to reproduce, has no functional impact and is also seen in upstream devices as explained the description above.  However, the RC of why this is happening is still unknown. 
Thus backporting this commit to print more info and change the verbosity to WARN

Ignore table if the EFI memory attributes are corrupt

---

patch/0001-prevent-bridge-link-show-failure-for-non-eswitch-allowed-devices.patch
patch/series

Backport https://github.com/torvalds/linux/commit/e92df790d07a8eea873efcb84776e7b71f81c7d5 into sonic-linux-kernel
On SmartSwitch we see the following error when hostside PF interfaces (for DPUs) created by mlx5_core driver are present.
```
root@sonic:/home/admin/# bridge vlan show
port              vlan-id
***                ***
RTNETLINK answers: Operation not permitted
Dump terminated
```
Similar error is seen for bridge link show command as well.
This backport is expected to fix these issues.

Add upstream fix for bridge link show failure
